import assert from "node:assert/strict";
import test from "node:test";

import { parseContentDispositionFilename } from "../app/lib/content-disposition.ts";

test("decodes the RFC 2047 filename generated by Spring", () => {
  const filename = "월간 발표 대본.pdf";
  const header = `attachment; filename="=?UTF-8?Q?${encodeMimeQuotedPrintable(filename)}?="`;

  assert.equal(parseContentDispositionFilename(header), filename);
});

test("prefers an RFC 5987 filename when both formats are present", () => {
  const header = `attachment; filename="fallback.pdf"; filename*=UTF-8''${encodeURIComponent("운영 가이드.pdf")}`;

  assert.equal(parseContentDispositionFilename(header), "운영 가이드.pdf");
});

test("supports RFC 2047 base64 and plain quoted filenames", () => {
  const filename = "회의록.pdf";
  const bytes = new TextEncoder().encode(filename);
  const payload = btoa(String.fromCharCode(...bytes));

  assert.equal(parseContentDispositionFilename(`attachment; filename="=?UTF-8?B?${payload}?="`), filename);
  assert.equal(parseContentDispositionFilename('attachment; filename="report.pdf"'), "report.pdf");
});

test("uses a safe filename for missing or path-like values", () => {
  assert.equal(parseContentDispositionFilename(null), "docgrid-document");
  assert.equal(parseContentDispositionFilename('attachment; filename="../../report.pdf"'), "report.pdf");
  assert.equal(parseContentDispositionFilename('attachment; filename=".."'), "docgrid-document");
});

function encodeMimeQuotedPrintable(value: string): string {
  return Array.from(new TextEncoder().encode(value), (byte) => {
    if (byte === 0x20) return "_";
    if ((byte >= 0x30 && byte <= 0x39) || (byte >= 0x41 && byte <= 0x5a) || (byte >= 0x61 && byte <= 0x7a) || byte === 0x2e) {
      return String.fromCharCode(byte);
    }
    return `=${byte.toString(16).toUpperCase().padStart(2, "0")}`;
  }).join("");
}
