import type { ApiEnvelope, ApiErrorBody } from "./api-types";
import { parseContentDispositionFilename } from "./content-disposition";

export const ACCESS_TOKEN_KEY = "docgrid.access-token";
export const AUTH_EXPIRED_EVENT = "docgrid:auth-expired";

/** Represents an HTTP failure returned by the DocGrid backend boundary. */
export class ApiError extends Error {
  readonly status: number;
  readonly code?: string;

  constructor(status: number, message: string, code?: string) {
    super(message);
    this.name = "ApiError";
    this.status = status;
    this.code = code;
  }
}

type RequestOptions = Omit<RequestInit, "body"> & {
  body?: BodyInit | Record<string, unknown> | null;
  auth?: boolean;
};

export async function apiRequest<T>(path: string, options: RequestOptions = {}): Promise<T> {
  const headers = new Headers(options.headers);
  const auth = options.auth !== false;
  const isFormData = typeof FormData !== "undefined" && options.body instanceof FormData;
  let body: BodyInit | null | undefined = options.body as BodyInit | null | undefined;

  // 1. Serialize JSON while preserving multipart boundaries generated by the browser.
  if (options.body && !isFormData && typeof options.body === "object") {
    headers.set("Content-Type", "application/json");
    body = JSON.stringify(options.body);
  }
  headers.set("Accept", "application/json");

  // 2. Attach the DocGrid JWT only to authenticated backend requests.
  if (auth && typeof window !== "undefined") {
    const token = window.sessionStorage.getItem(ACCESS_TOKEN_KEY);
    if (token) headers.set("Authorization", `Bearer ${token}`);
  }

  const response = await fetch(`/api/backend${path}`, {
    ...options,
    headers,
    body,
    cache: "no-store",
  });

  // 3. A 401 invalidates the in-tab session so protected screens cannot display stale data.
  if (response.status === 401 && auth && typeof window !== "undefined") {
    window.sessionStorage.removeItem(ACCESS_TOKEN_KEY);
    window.dispatchEvent(new Event(AUTH_EXPIRED_EVENT));
  }

  if (response.status === 204) return undefined as T;

  const text = await response.text();
  const payload = text ? safeJson(text) : null;
  if (!response.ok) {
    const error = (payload ?? {}) as ApiErrorBody;
    // 4. Convert a plain-text proxy rejection into an actionable upload message.
    const fallbackMessage = response.status === 413 ? "파일 용량이 큽니다." : "요청을 처리하지 못했습니다.";
    throw new ApiError(response.status, error.message ?? fallbackMessage, error.code);
  }

  return (payload as ApiEnvelope<T>).data;
}

export async function downloadBackendFile(path: string): Promise<void> {
  const file = await fetchBackendFile(path);
  const objectUrl = URL.createObjectURL(file.blob);
  const anchor = document.createElement("a");
  anchor.href = objectUrl;
  anchor.download = file.filename;
  document.body.append(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(objectUrl);
}

export async function previewBackendFile(path: string): Promise<void> {
  const previewWindow = window.open("", "_blank");
  if (!previewWindow) throw new ApiError(0, "브라우저에서 원본 미리보기 팝업을 허용해 주세요.");
  previewWindow.opener = null;

  try {
    const file = await fetchBackendFile(path);
    const objectUrl = URL.createObjectURL(file.blob);
    previewWindow.location.href = objectUrl;
    window.setTimeout(() => URL.revokeObjectURL(objectUrl), 60_000);
  } catch (reason) {
    previewWindow.close();
    throw reason;
  }
}

async function fetchBackendFile(path: string): Promise<{ blob: Blob; filename: string }> {
  const headers = new Headers({ Accept: "application/octet-stream" });
  const token = window.sessionStorage.getItem(ACCESS_TOKEN_KEY);
  if (token) headers.set("Authorization", `Bearer ${token}`);

  // 1. Fetch the protected file through the same-origin proxy with the DocGrid token.
  const response = await fetch(`/api/backend${path}`, { headers, cache: "no-store" });
  if (response.status === 401) {
    window.sessionStorage.removeItem(ACCESS_TOKEN_KEY);
    window.dispatchEvent(new Event(AUTH_EXPIRED_EVENT));
  }
  if (!response.ok) {
    const payload = safeJson(await response.text()) as ApiErrorBody | null;
    throw new ApiError(response.status, payload?.message ?? "원본 파일을 불러오지 못했습니다.", payload?.code);
  }

  // 2. Preserve the MIME type and decode both browser and Spring filename formats.
  const filename = parseContentDispositionFilename(response.headers.get("content-disposition"));
  return { blob: await response.blob(), filename };
}

function safeJson(value: string): unknown {
  try {
    return JSON.parse(value);
  } catch {
    return null;
  }
}

export function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : "알 수 없는 오류가 발생했습니다.";
}

export function toQuery(params: Record<string, string | number | null | undefined>): string {
  const search = new URLSearchParams();
  Object.entries(params).forEach(([key, value]) => {
    if (value !== null && value !== undefined && value !== "") search.set(key, String(value));
  });
  const query = search.toString();
  return query ? `?${query}` : "";
}
